# Module 1: Data validation and pre-processing technique

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-1.3.4-cp38-cp38-win_amd64.whl (10.2 MB)
Collecting numpy>=1.17.3
  Downloading numpy-1.21.4-cp38-cp38-win_amd64.whl (14.0 MB)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hp\anaconda3\envs\ravi\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2017.3
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\envs\ravi\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.21.4 pandas-1.3.4 pytz-2021.3
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install numpy

Requirement already satisfied: numpy in c:\users\hp\anaconda3\envs\ravi\lib\site-packages (1.21.4)
Note: you may need to restart the kernel to use updated packages.

In [24]:
#import library packages
import pandas as pd
import numpy as np

In [25]:
import warnings
warnings.filterwarnings("ignore")

In [26]:
#Load given dataset
data = pd.read_csv("drug.csv")

Before drop the given dataset:

In [4]:
data.head(10)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,condition,review,rating,date,usefulCount,drugName
0,0,148873,149718,73450,Birth Control,"""I loved this pill at first, it got rid if my ...",4,"November 28, 2013",22,Ethinyl estradiol / norethindrone
1,1,142496,143318,73600,Birth Control,"""I started taking the pill a little over a mon...",5,"May 28, 2013",6,Ethinyl estradiol / norethindrone
2,2,102598,103191,72720,Birth Control,"""This is the first pill that I&#039;ve tried w...",7,"August 28, 2015",2,Ethinyl estradiol / norethindrone
3,3,559,562,72638,Birth Control,"""I&#039;ve been on Junel Fe for 9 months now. ...",3,"September 22, 2015",5,Ethinyl estradiol / norethindrone
4,4,73183,73619,16494,Birth Control,"""This pill overall is not good. its been about...",2,"December 25, 2015",15,Ethinyl estradiol / norethindrone
5,5,20392,20516,73221,Birth Control,"""Well the first 2 months on Microgestin Fe 1/2...",7,"September 2, 2014",4,Ethinyl estradiol / norethindrone
6,6,94025,94579,73435,Birth Control,"""I take this birth control mainly for cramps, ...",8,"October 29, 2013",5,Ethinyl estradiol / norethindrone
7,7,140268,141075,74585,Abnormal Uterine Bleeding,"""I have been on this pill for 2 weeks. I took ...",1,"July 17, 2009",29,Levonorgestrel
8,8,141511,142330,72659,Birth Control,"""I was never able to take &quot;the pill&quot;...",10,"September 11, 2015",12,Ethinyl estradiol / norethindrone
9,9,68317,68730,16079,Birth Control,"""I stopped and restarted this BC to see if may...",3,"May 25, 2016",5,Ethinyl estradiol / norethindrone

In [5]:
#shape
data.shape

(18160, 10)

After drop the given dataset:

In [6]:
df = data.dropna()

In [7]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,condition,review,rating,date,usefulCount,drugName
0,0,148873,149718,73450,Birth Control,"""I loved this pill at first, it got rid if my ...",4,"November 28, 2013",22,Ethinyl estradiol / norethindrone
1,1,142496,143318,73600,Birth Control,"""I started taking the pill a little over a mon...",5,"May 28, 2013",6,Ethinyl estradiol / norethindrone
2,2,102598,103191,72720,Birth Control,"""This is the first pill that I&#039;ve tried w...",7,"August 28, 2015",2,Ethinyl estradiol / norethindrone
3,3,559,562,72638,Birth Control,"""I&#039;ve been on Junel Fe for 9 months now. ...",3,"September 22, 2015",5,Ethinyl estradiol / norethindrone
4,4,73183,73619,16494,Birth Control,"""This pill overall is not good. its been about...",2,"December 25, 2015",15,Ethinyl estradiol / norethindrone

In [8]:
#shape
df.shape

(18160, 10)

In [9]:
#columns
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1',
       'condition', 'review', 'rating', 'date', 'usefulCount', 'drugName'],
      dtype='object')

In [10]:
#To describe the dataframe
df.describe()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,rating,usefulCount
count,18160.00000,18160.000000,18160.000000,18160.000000,18160.000000,18160.000000
mean,9079.50000,81115.433590,81587.098954,111612.652093,6.065308,7.792676
std,5242.48478,46493.744772,46754.677067,55140.459779,3.373875,16.078814
min,0.00000,6.000000,6.000000,14648.000000,1.000000,0.000000
25%,4539.75000,40781.750000,41029.750000,83921.000000,3.000000,2.000000
50%,9079.50000,81946.000000,82431.000000,109109.500000,7.000000,4.000000
75%,13619.25000,121280.500000,121975.500000,143960.250000,9.000000,9.000000
max,18159.00000,160374.000000,161273.000000,228283.000000,10.000000,1247.000000

In [11]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18160 entries, 0 to 18159
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        18160 non-null  int64
 1   Unnamed: 0.1      18160 non-null  int64
 2   Unnamed: 0.1.1    18160 non-null  int64
 3   Unnamed: 0.1.1.1  18160 non-null  int64
 4   condition         18160 non-null  object
 5   review            18160 non-null  object
 6   rating            18160 non-null  int64
 7   date              18160 non-null  object
 8   usefulCount       18160 non-null  int64
 9   drugName          18160 non-null  object
dtypes: int64(6), object(4)
memory usage: 1.5+ MB

Checking duplicate values of dataframe

In [12]:
#Checking for duplicate data
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18155    False
18156    False
18157    False
18158    False
18159    False
Length: 18160, dtype: bool

In [13]:
sum(df.duplicated())

0

In [14]:
#Checking sum of missing values
df.isnull().sum()

Unnamed: 0          0
Unnamed: 0.1        0
Unnamed: 0.1.1      0
Unnamed: 0.1.1.1    0
condition           0
review              0
rating              0
date                0
usefulCount         0
drugName            0
dtype: int64

In [15]:
df.drugName.unique()

array(['Ethinyl estradiol / norethindrone', 'Levonorgestrel',
       'Ethinyl estradiol / norgestimate', 'Etonogestrel', 'Nexplanon'],
      dtype=object)

In [16]:
df.drugName.value_counts()

Ethinyl estradiol / norethindrone    3632
Levonorgestrel                       3632
Ethinyl estradiol / norgestimate     3632
Etonogestrel                         3632
Nexplanon                            3632
Name: drugName, dtype: int64

In [17]:
df.rating.unique()

array([ 4,  5,  7,  3,  2,  8,  1, 10,  9,  6], dtype=int64)

In [18]:
df.corr()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,rating,usefulCount
Unnamed: 0,1.000000,-0.003934,-0.003937,0.124850,0.019743,-0.007615
Unnamed: 0.1,-0.003934,1.000000,1.000000,0.002329,0.005899,0.009497
Unnamed: 0.1.1,-0.003937,1.000000,1.000000,0.002331,0.005900,0.009499
Unnamed: 0.1.1.1,0.124850,0.002329,0.002331,1.000000,0.132151,0.021823
rating,0.019743,0.005899,0.005900,0.132151,1.000000,0.141144
usefulCount,-0.007615,0.009497,0.009499,0.021823,0.141144,1.000000

In [19]:
df.groupby('drugName').describe()

                                  Unnamed: 0                             \
                                       count          mean          std
drugName
Ethinyl estradiol / norethindrone     3632.0   4525.061674  5602.997227
Ethinyl estradiol / norgestimate      3632.0   8964.070760  5886.409388
Etonogestrel                          3632.0   7306.555892  2967.614304
Levonorgestrel                        3632.0   9916.270925  1061.004519
Nexplanon                             3632.0  14685.540749  2330.188704

                                                                         \
                                       min       25%      50%       75%
drugName
Ethinyl estradiol / norethindrone      0.0    908.75   1816.5   2724.25
Ethinyl estradiol / norgestimate    2750.0   3657.75   4565.5  15464.25
Etonogestrel                        4783.0   5690.75   6598.5   7506.25
Levonorgestrel                         7.0   9010.75   9918.5  10826.25
Nexplanon                          11735.0  12642.75  13550.5  17251.25

                                           Unnamed: 0.1                ...  \
                                       max        count          mean  ...
drugName                                                               ...
Ethinyl estradiol / norethindrone  14773.0       3632.0  82209.519273  ...
Ethinyl estradiol / norgestimate   16372.0       3632.0  80942.205396  ...
Etonogestrel                       16683.0       3632.0  81500.245595  ...
Levonorgestrel                     11734.0       3632.0  80071.927863  ...
Nexplanon                          18159.0       3632.0  80853.269824  ...

                                  rating       usefulCount             \
                                     75%   max       count       mean
drugName
Ethinyl estradiol / norethindrone    9.0  10.0      3632.0   7.701817
Ethinyl estradiol / norgestimate     9.0  10.0      3632.0   8.327643
Etonogestrel                         9.0  10.0      3632.0   6.628579
Levonorgestrel                      10.0  10.0      3632.0  10.087280
Nexplanon                            9.0  10.0      3632.0   6.218062


                                         std  min  25%  50%   75%     max
drugName
Ethinyl estradiol / norethindrone  11.245809  0.0  2.0  5.0   9.0   182.0
Ethinyl estradiol / norgestimate   12.399862  0.0  2.0  5.0  10.0   229.0
Etonogestrel                       13.986971  0.0  1.0  4.0   7.0   448.0
Levonorgestrel                     26.974438  0.0  2.0  5.0  11.0  1247.0
Nexplanon                           8.947001  0.0  2.0  4.0   7.0   132.0

[5 rows x 48 columns]

In [20]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1',
       'condition', 'review', 'rating', 'date', 'usefulCount', 'drugName'],
      dtype='object')

In [21]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,condition,review,rating,date,usefulCount,drugName
0,0,148873,149718,73450,Birth Control,"""I loved this pill at first, it got rid if my ...",4,"November 28, 2013",22,Ethinyl estradiol / norethindrone
1,1,142496,143318,73600,Birth Control,"""I started taking the pill a little over a mon...",5,"May 28, 2013",6,Ethinyl estradiol / norethindrone
2,2,102598,103191,72720,Birth Control,"""This is the first pill that I&#039;ve tried w...",7,"August 28, 2015",2,Ethinyl estradiol / norethindrone
3,3,559,562,72638,Birth Control,"""I&#039;ve been on Junel Fe for 9 months now. ...",3,"September 22, 2015",5,Ethinyl estradiol / norethindrone
4,4,73183,73619,16494,Birth Control,"""This pill overall is not good. its been about...",2,"December 25, 2015",15,Ethinyl estradiol / norethindrone

In [25]:
pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.tar.gz (1.1 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.0.1-cp38-cp38-win_amd64.whl (7.2 MB)
Collecting joblib>=0.11
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Requirement already satisfied: numpy>=1.14.6 in c:\users\hp\anaconda3\envs\ravi\lib\site-packages (from scikit-learn->sklearn) (1.21.4)
Collecting scipy>=1.1.0
  Downloading scipy-1.7.2-cp38-cp38-win_amd64.whl (34.2 MB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py): started
  Building wheel for sklearn (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=cb10eb07a50a03ff0d8b2bceb6d6ff0c2f61a56f2987ea812a7681bc38bc2efc
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, sklearn
Successfully installed joblib-1.1.0 scikit-learn-1.0.1 scipy-1.7.2 sklearn-0.0 threadpoolctl-3.0.0
Note: you may need to restart the kernel to use updated packages.

In [22]:
from sklearn.preprocessing import LabelEncoder
var=['drugName', 'condition', 'review', 'rating','date']
le=LabelEncoder()
for i in var:
   df[i]=le.fit_transform(df[i]).astype(int)

In [23]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,condition,review,rating,date,usefulCount,drugName
0,0,148873,149718,73450,8,5820,3,2181,22,0
1,1,142496,143318,73600,8,6179,4,1945,6,0
2,2,102598,103191,72720,8,11384,6,376,2,0
3,3,559,562,72638,8,7869,2,2613,5,0
4,4,73183,73619,16494,8,11518,1,583,15,0

In [41]:
df.corr()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,condition,review,rating,date,usefulCount,drugName
Unnamed: 0,1.000000,-0.003934,-0.003937,0.124850,-0.028537,-0.047663,0.019743,0.003762,-0.007615,0.573881
Unnamed: 0.1,-0.003934,1.000000,1.000000,0.002329,-0.007730,0.009506,0.005899,-0.009741,0.009497,-0.010898
Unnamed: 0.1.1,-0.003937,1.000000,1.000000,0.002331,-0.007728,0.009505,0.005900,-0.009745,0.009499,-0.010897
Unnamed: 0.1.1.1,0.124850,0.002329,0.002331,1.000000,0.008352,-0.112116,0.132151,0.013598,0.021823,0.498067
condition,-0.028537,-0.007730,-0.007728,0.008352,1.000000,0.033326,0.100061,-0.017023,0.011899,-0.015484
review,-0.047663,0.009506,0.009505,-0.112116,0.033326,1.000000,-0.040476,-0.016537,0.003078,-0.103397
rating,0.019743,0.005899,0.005900,0.132151,0.100061,-0.040476,1.000000,-0.016460,0.141144,0.071152
date,0.003762,-0.009741,-0.009745,0.013598,-0.017023,-0.016537,-0.016460,1.000000,-0.015211,0.020312
usefulCount,-0.007615,0.009497,0.009499,0.021823,0.011899,0.003078,0.141144,-0.015211,1.000000,-0.010624
drugName,0.573881,-0.010898,-0.010897,0.498067,-0.015484,-0.103397,0.071152,0.020312,-0.010624,1.000000